"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load .env file if it exists (for local development)
env_path = os.path.join(Path(__file__).resolve().parent.parent, '.env')
if os.path.exists(env_path):
    load_dotenv(env_path)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ValueError("SECRET_KEY environment variable is not set. Please set it in your environment variables.")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Get Render service URL from environment or use default
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME', '')
ALLOWED_HOSTS_ENV = os.environ.get('ALLOWED_HOSTS', '')

if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS = [RENDER_EXTERNAL_HOSTNAME]
elif ALLOWED_HOSTS_ENV:
    ALLOWED_HOSTS = [host.strip() for host in ALLOWED_HOSTS_ENV.split(',')]
else:
    # Default for local development
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'cv-converter-agent.onrender.com']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary_storage',  # Must be before staticfiles
    'django.contrib.staticfiles',
    'whitenoise.runserver_nostatic',  # Use whitenoise for static files
    'cloudinary',  # Add cloudinary app
    'corsheaders',
    'rest_framework',
    'rest_framework.authtoken',
    'apps.cv',
    'apps.users',
    'apps.llm',
    'apps.api',
    'apps.interview',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add whitenoise middleware
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
#
# Use PostgreSQL with DATABASE_URL from environment variables
import dj_database_url

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Parse DATABASE_URL and add connection options for Render
    db_config = dj_database_url.parse(
        DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
    # Add SSL requirement for cloud databases (Supabase, etc.) if not already set
    if 'OPTIONS' not in db_config:
        db_config['OPTIONS'] = {}
    if 'sslmode' not in db_config['OPTIONS']:
        db_config['OPTIONS']['sslmode'] = 'require'
    DATABASES = {
        "default": db_config
    }
else:
    # Fallback to individual environment variables
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.environ.get("POSTGRES_DB", "postgres"),
            "USER": os.environ.get("POSTGRES_USER", "postgres"),
            "PASSWORD": os.environ.get("POSTGRES_PASSWORD", ""),
            "HOST": os.environ.get("POSTGRES_HOST", "localhost"),
            "PORT": os.environ.get("POSTGRES_PORT", "5432"),
            "CONN_MAX_AGE": 600,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(str(BASE_DIR), 'staticfiles')

# WhiteNoise for static files is configured in STORAGES['staticfiles'] below.

MEDIA_ROOT = os.path.join(str(BASE_DIR), 'media')
# When using Cloudinary, MEDIA_URL is overridden by the storage backend (HTTPS Cloudinary URLs).
# Keep a fallback for local dev if Cloudinary is not configured.
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# Allow the Next.js dev server (and other origins in development) to call the API.
# For production, this should be tightened to explicit allowed origins.
CORS_ALLOW_ALL_ORIGINS = True

# Cloudinary Storage Configuration
# This tells Django to use Cloudinary instead of the local disk
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.environ.get('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.environ.get('CLOUDINARY_API_KEY'),
    'API_SECRET': os.environ.get('CLOUDINARY_API_SECRET'),
    # Ensure secure URLs (HTTPS)
    'SECURE': True,
}

# Log Cloudinary configuration status (without exposing secrets)
has_cloud_name = bool(CLOUDINARY_STORAGE.get('CLOUD_NAME'))
has_api_key = bool(CLOUDINARY_STORAGE.get('API_KEY'))
has_api_secret = bool(CLOUDINARY_STORAGE.get('API_SECRET'))
cloudinary_configured = has_cloud_name and has_api_key and has_api_secret

print(f"[CLOUDINARY] Configuration check:")
print(f"  CLOUD_NAME: {'✅ ' + CLOUDINARY_STORAGE.get('CLOUD_NAME') if has_cloud_name else '❌ MISSING'}")
print(f"  API_KEY: {'✅ SET' if has_api_key else '❌ MISSING'}")
print(f"  API_SECRET: {'✅ SET' if has_api_secret else '❌ MISSING'}")

if cloudinary_configured:
    print(f"✅ [CLOUDINARY] All credentials loaded - files will be stored on Cloudinary")
else:
    missing = []
    if not has_cloud_name: missing.append('CLOUDINARY_CLOUD_NAME')
    if not has_api_key: missing.append('CLOUDINARY_API_KEY')
    if not has_api_secret: missing.append('CLOUDINARY_API_SECRET')
    print(f"⚠️  [CLOUDINARY] Missing: {', '.join(missing)}")
    print(f"⚠️  [CLOUDINARY] Files will fall back to local storage (ephemeral on Render!)")


# File Storage Configuration
# Note: Using deprecated settings (DEFAULT_FILE_STORAGE, STATICFILES_STORAGE) instead of
# the new STORAGES dict because django-cloudinary-storage 0.3.0 doesn't support the new format.
# This is compatible with Django 5.2 which still supports these deprecated settings.

# Media files (user uploads) - stored on Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.RawMediaCloudinaryStorage'

# Static files (CSS, JS) - served by WhiteNoise
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'


