# Generated by Django 4.2.7 on 2026-01-20 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetencePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_type', models.CharField(choices=[('original', 'Original'), ('interview_based', 'Interview Based')], max_length=20)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competence_papers', to='cv.cv')),
            ],
            options={
                'verbose_name': 'Competence Paper',
                'verbose_name_plural': 'Competence Papers',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('work_experience', 'Work Experience'), ('skill', 'Skill'), ('language', 'Language'), ('training', 'Training'), ('education', 'Education'), ('certification', 'Certification'), ('project', 'Project'), ('discovery', 'Discovery'), ('other', 'Other')], max_length=20)),
                ('topic', models.CharField(help_text='What specifically is being asked about (e.g., "Python", "5 years at Google")', max_length=255)),
                ('question_text', models.TextField(help_text='The actual question')),
                ('question_order', models.IntegerField(help_text='Order in sequence')),
                ('phase', models.CharField(choices=[('validation', 'Validation'), ('discovery', 'Discovery')], default='validation', max_length=20)),
                ('asked_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ('question_order', 'asked_at'),
            },
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('comparison_results', models.JSONField(blank=True, default=dict, help_text='Stores confirmed/unconfirmed/partial/new items with full HR responses')),
                ('hr_recommendation', models.TextField(blank=True, help_text="HR's full recommendation text")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='cv.cv')),
                ('interview_competence_paper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_sessions', to='interview.competencepaper')),
                ('original_competence_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_sessions', to='interview.competencepaper')),
            ],
            options={
                'verbose_name': 'Interview Session',
                'verbose_name_plural': 'Interview Sessions',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='InterviewResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(help_text='Full transcribed answer from HR')),
                ('answer_audio_url', models.URLField(blank=True, help_text='Optional audio file storage', null=True)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('partially_confirmed', 'Partially Confirmed'), ('not_confirmed', 'Not Confirmed'), ('new_skill', 'New Skill')], max_length=20)),
                ('confidence_level', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=10, null=True)),
                ('extracted_skills', models.JSONField(blank=True, default=list, help_text='If new skills mentioned, store them here')),
                ('notes', models.TextField(blank=True, help_text='Additional processing notes')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='interview.interviewquestion')),
            ],
            options={
                'verbose_name': 'Interview Response',
                'verbose_name_plural': 'Interview Responses',
                'ordering': ('answered_at',),
            },
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='interview.interviewsession'),
        ),
        migrations.AddField(
            model_name='competencepaper',
            name='interview_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competence_papers', to='interview.interviewsession'),
        ),
        migrations.AddIndex(
            model_name='interviewsession',
            index=models.Index(fields=['cv', 'status'], name='interview_i_cv_id_64c3d5_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['session', 'question_order'], name='interview_i_session_3ef75e_idx'),
        ),
        migrations.AddIndex(
            model_name='interviewquestion',
            index=models.Index(fields=['category'], name='interview_i_categor_edbdb1_idx'),
        ),
        migrations.AddIndex(
            model_name='competencepaper',
            index=models.Index(fields=['cv', 'paper_type'], name='interview_c_cv_id_32ac59_idx'),
        ),
    ]
