# Generated by Django 4.2.7 on 2026-01-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0001_initial'),
    ]

    operations = [
        # Rename models
        migrations.RenameModel(
            old_name='InterviewSession',
            new_name='ConversationSession',
        ),
        migrations.RenameModel(
            old_name='InterviewQuestion',
            new_name='ConversationQuestion',
        ),
        migrations.RenameModel(
            old_name='InterviewResponse',
            new_name='ConversationResponse',
        ),
        # Rename field in CompetencePaper
        migrations.RenameField(
            model_name='competencepaper',
            old_name='interview_session',
            new_name='conversation_session',
        ),
    ]
