# Generated by Django 4.2.7 on 2026-01-20 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
        ('interview', '0002_rename_to_conversation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversationquestion',
            options={'ordering': ('question_order', 'asked_at'), 'verbose_name': 'Conversation Question', 'verbose_name_plural': 'Conversation Questions'},
        ),
        migrations.AlterModelOptions(
            name='conversationresponse',
            options={'ordering': ('answered_at',), 'verbose_name': 'Conversation Response', 'verbose_name_plural': 'Conversation Responses'},
        ),
        migrations.AlterModelOptions(
            name='conversationsession',
            options={'ordering': ('-created_at',), 'verbose_name': 'Conversation Session', 'verbose_name_plural': 'Conversation Sessions'},
        ),
        migrations.RenameIndex(
            model_name='competencepaper',
            new_name='conversatio_cv_id_ed254c_idx',
            old_name='interview_c_cv_id_32ac59_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationquestion',
            new_name='conversatio_session_46c270_idx',
            old_name='interview_i_session_3ef75e_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationquestion',
            new_name='conversatio_categor_996093_idx',
            old_name='interview_i_categor_edbdb1_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationsession',
            new_name='conversatio_cv_id_a3f019_idx',
            old_name='interview_i_cv_id_64c3d5_idx',
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='cv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to='cv.cv'),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='interview_competence_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='interview.competencepaper'),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='original_competence_paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_conversations', to='interview.competencepaper'),
        ),
        migrations.AlterModelTable(
            name='competencepaper',
            table='conversation_competencepaper',
        ),
        migrations.AlterModelTable(
            name='conversationquestion',
            table='conversation_question',
        ),
        migrations.AlterModelTable(
            name='conversationresponse',
            table='conversation_response',
        ),
        migrations.AlterModelTable(
            name='conversationsession',
            table='conversation_session',
        ),
    ]
