# Generated by Django 4.2.7 on 2026-01-20 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0003_change_table_names'),
    ]

    operations = [
        # First, rename the old table to avoid conflict
        migrations.AlterModelTable(
            name='competencepaper',
            table='competence_paper',
        ),
        # Remove old fields and indexes
        migrations.RemoveIndex(
            model_name='competencepaper',
            name='conversatio_cv_id_ed254c_idx',
        ),
        migrations.RemoveField(
            model_name='competencepaper',
            name='conversation_session',
        ),
        migrations.RemoveField(
            model_name='competencepaper',
            name='paper_type',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='interview_competence_paper',
        ),
        # Add new index for competencepaper
        migrations.AddIndex(
            model_name='competencepaper',
            index=models.Index(fields=['cv', 'created_at'], name='competence__cv_id_3ffd2d_idx'),
        ),
        # Now create the new ConversationCompetencePaper model (table will be conversation_competencepaper)
        migrations.CreateModel(
            name='ConversationCompetencePaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_competence_papers', to='interview.conversationsession')),
            ],
            options={
                'verbose_name': 'Conversation Competence Paper',
                'verbose_name_plural': 'Conversation Competence Papers',
                'db_table': 'conversation_competencepaper',
                'ordering': ('-created_at',),
            },
        ),
        # Add field to ConversationSession
        migrations.AddField(
            model_name='conversationsession',
            name='conversation_competence_paper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversation_sessions', to='interview.conversationcompetencepaper'),
        ),
        # Add index for ConversationCompetencePaper
        migrations.AddIndex(
            model_name='conversationcompetencepaper',
            index=models.Index(fields=['conversation_session', 'created_at'], name='conversatio_convers_ee2a41_idx'),
        ),
    ]
