# Generated by Django 5.2.9 on 2026-01-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0005_add_section_to_conversation_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='completed_sections',
            field=models.JSONField(blank=True, default=list, help_text='List of section keys that have been completed (e.g., ["core_skills", "soft_skills"])'),
        ),
    ]
