# Generated by Django 5.2.9 on 2026-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0006_add_completed_sections_to_conversation_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationsession',
            name='completed_sections',
        ),
        migrations.AlterField(
            model_name='conversationquestion',
            name='section',
            field=models.CharField(choices=[('core_skills', 'Core Skills'), ('soft_skills', 'Soft Skills'), ('languages', 'Languages'), ('education', 'Education'), ('trainings_certifications', 'Trainings & Certifications'), ('technical_competencies', 'Technical Competencies'), ('project_experience', 'Project Experience'), ('overall_assessment', 'Overall Assessment & Recommendation')], default='core_skills', help_text='Logical section this question belongs to (e.g., core_skills, soft_skills, etc.)', max_length=50),
        ),
    ]
