# Generated by Django 4.2.7 on 2026-01-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0007_remove_conversationsession_completed_sections_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationquestion',
            name='category',
            field=models.CharField(choices=[('work_experience', 'Work Experience'), ('skill', 'Skill'), ('language', 'Language'), ('training', 'Training'), ('education', 'Education'), ('certification', 'Certification'), ('project', 'Project'), ('discovery', 'Discovery'), ('recommendation', 'Recommendation'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conversationquestion',
            name='section',
            field=models.CharField(choices=[('core_skills', 'Core Skills'), ('soft_skills', 'Soft Skills'), ('languages', 'Languages'), ('education', 'Education'), ('trainings_certifications', 'Trainings & Certifications'), ('technical_competencies', 'Technical Competencies'), ('project_experience', 'Project Experience'), ('recommendations', 'Recommendations'), ('additional_info', 'Additional Information')], default='core_skills', help_text='Logical section this question belongs to (e.g., core_skills, soft_skills, etc.)', max_length=50),
        ),
    ]
