# Generated by Django 5.2.9 on 2026-01-28 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0008_alter_conversationquestion_category_and_more'),
        ('interview', '0008_alter_conversationquestion_section'),
    ]

    operations = [
    ]
