# Generated by Django 4.2.7 on 2026-02-11 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0009_merge_20260128_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversationresponse',
            name='answer_audio_url',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='comparison_results',
        ),
        migrations.RemoveField(
            model_name='conversationsession',
            name='hr_recommendation',
        ),
    ]
