# Generated by Django 5.2.8 on 2026-02-13 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0010_remove_unused_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationsession',
            name='cv_extracted_text',
            field=models.TextField(blank=True, help_text='Cached CV text to prevent re-downloading and re-parsing on every API call', null=True),
        ),
    ]
