# Generated by Django 5.2.8 on 2026-04-20 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview', '0013_drop_transcript_columns_after_revert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationsession',
            name='cv_extracted_text',
            field=models.TextField(blank=True, help_text='Competence Paper text extracted from CV at time of conversation', null=True),
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
